### ISSUE TITLE
Question about the conversion to unity 2019

### ISSUE THREAD

**Issue by kzgamer** [esperecyan/VRMConverterForVRChat#15]
Is the plugin going to be updated to support unity 2019? I mainly work with VRM models for VRC and I'm not sure if you are going to update it to support the new version

**Comment by esperecyan** [comment]
Are you experiencing any problems?

**Comment by UwUbunn** [comment]
I'm particularly having problems due to the shift, unity keeps crashing when I try to upload the converted model with the current version of the plugin. It doesn't seem to be working for unity 2019

**Comment by esperecyan** [comment]
Isn't this a problem with the VRChat SDK?　I also had Unity freeze when I tried to build with VRChat SDK3-World.　Perhaps you can improve it by rebuilding the project.

**Comment by UwUbunn** [comment]
Using the SDK2 only makes it work for Windows.  If I try to upload for quest a message keeps popping up that I need to add an 'animator' and then it doesn't detect the model as humanoid, it just overall breaks
![unknown](https://user-images.githubusercontent.com/88593843/128653469-8d06c25c-3cf9-4f53-aed7-fd893133ca1a.png)

![Screenshot 2021-08-08 213645](https://user-images.githubusercontent.com/88593843/128652635-be3c8b1a-06a7-45ee-83d6-63287be058a7.jpg)

**Comment by fire** [comment]
I am unable to import VRChat character to convert to vrm.

**Comment by esperecyan** [comment]
@fire Are you saying that Unity 2018.4 can convert VRChat character to VRM successfully, but Unity 2019.4 outputs a broken VRM?　Can you please tell me the steps to reproduce this?

**Comment by esperecyan** [comment]
@fire This appears to be a separate issue from Unity 2019.4. Please create a new issue with a model I can reproduce or how to reproduce it.
