### ISSUE TITLE
VRoid正式版アバターで腰が曲がる問題

### ISSUE THREAD

**Issue by pureiyaya** [esperecyan/VRMConverterForVRChat#22]
VRoid正式版でコンバートしたアバターでフルトラッキングみた結果、以前の様な腰が曲がった状態になったので報告させていただきます。
![VRChat_1920x1080_2021-10-31_22-39-07 840](https://user-images.githubusercontent.com/93482509/139591037-e1b66785-334d-4460-9723-f19012c4b21b.png)

**Comment by esperecyan** [comment]
恐らくVRoid Studioのデフォルトの身長で、両手間の距離とと視点の高さが一致していないためではないかと思いますが、いかがでしょうか？

**Comment by esperecyan** [comment]
VRChatへUpperChestが存在するモデルをアップロードできなかった頃に実装していた、UpperChestを削除する機能を復活させたところ問題を回避できているように見えるので、v30.0.0で実装しました
