### ISSUE TITLE
ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by sas190** [esperecyan/VRMConverterForVRChat#23]
unity 2019.4.31f1

VRC SDK 3

ArgumentNullException: Value cannot be null.
Parameter name: type
System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Activator.CreateInstance (System.Type type) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Esperecyan.Unity.VRMConverterForVRChat.Components.ComponentsReplacer.ConvertVRMSpringBone (VRM.VRMSpringBone springBone, System.Collections.Generic.IDictionary`2[TKey,TValue] dynamicBoneColliderGroups, Esperecyan.Unity.VRMConverterForVRChat.Converter+SwayingParametersConverter swayingParametersConverter) (at Library/PackageCache/jp.pokemori.vrm-converter-for-vrchat@29.1.0/Editor/Components/ComponentsReplacer.cs:213)
Esperecyan.Unity.VRMConverterForVRChat.Components.ComponentsReplacer.ConvertVRMSpringBones (UnityEngine.GameObject avatar, System.Collections.Generic.IDictionary`2[TKey,TValue] dynamicBoneColliderGroups, Esperecyan.Unity.VRMConverterForVRChat.Converter+SwayingParametersConverter swayingParametersConverter) (at Library/PackageCache/jp.pokemori.vrm-converter-for-vrchat@29.1.0/Editor/Components/ComponentsReplacer.cs:160)
Esperecyan.Unity.VRMConverterForVRChat.Components.ComponentsReplacer.Apply (UnityEngine.GameObject avatar, Esperecyan.Unity.VRMConverterForVRChat.Converter+SwayingObjectsConverterSetting swayingObjectsConverterSetting, Esperecyan.Unity.VRMConverterForVRChat.Converter+SwayingParametersConverter swayingParametersConverter) (at Library/PackageCache/jp.pokemori.vrm-converter-for-vrchat@29.1.0/Editor/Components/ComponentsReplacer.cs:53)
Esperecyan.Unity.VRMConverterForVRChat.Converter.Convert (UnityEngine.GameObject prefabInstance, System.Collections.Generic.IEnumerable`1[T] clips, Esperecyan.Unity.VRMConverterForVRChat.Converter+SwayingObjectsConverterSetting swayingObjectsConverterSetting, System.Boolean takingOverSwayingParameters, Esperecyan.Unity.VRMConverterForVRChat.Converter+SwayingParametersConverter swayingParametersConverter, System.Boolean enableAutoEyeMovement, System.Single addedShouldersPositionY, System.Single moveEyeBoneToFrontForEyeMovement, System.Boolean forQuest, System.Single addedArmaturePositionY, System.Boolean useAnimatorForBlinks, System.Boolean useShapeKeyNormalsAndTangents, Esperecyan.Unity.VRMConverterForVRChat.VRMBlendShapeClip vrmBlendShapeForFINGERPOINT) (at Library/PackageCache/jp.pokemori.vrm-converter-for-vrchat@29.1.0/Editor/Converter.cs:134)
Esperecyan.Unity.VRMConverterForVRChat.UI.Wizard.OnWizardCreate () (at Library/PackageCache/jp.pokemori.vrm-converter-for-vrchat@29.1.0/Editor/UI/Wizard.cs:630)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.ScriptableWizard.OnGUI () (at <a259d3c004024353a2c217da97495055>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.OldOnGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <344226e341014466b33f0c0fa34fcef5>:0)

**Comment by esperecyan** [comment]
What kind of operation does this happen?
Can you provide model and steps to reproduce the problem?

**Comment by esperecyan** [comment]
There is no reply, so I close this.
