### ISSUE TITLE
VRMを変換した際、FXレイヤーに当てはまる「FX」が編集の出来ないものになっている

### ISSUE THREAD

**Issue by Rikurus** [esperecyan/VRMConverterForVRChat#30]
VRMアバターを本ツールを用いてVRChat用に変換した際、
自動で生成されるFXレイヤーのアニメーターコントローラーが設定値の編集の出来ない特殊なものになっています。
こちらは意図された仕様でしょうか。
![image](https://user-images.githubusercontent.com/51016253/150665035-07ab2a8b-6bab-4b65-91b8-0d93c6d9966f.png)

また、この状態でUnityを終了し再起動すると
下記画像のように設定されていたアニメーションが「None」になってしまいます。
![image](https://user-images.githubusercontent.com/51016253/150665118-1ced0198-b4a9-4be7-8899-5b4abcdcca7c.png)
※そのため、作業終了後にUnityを終了しその後Unityをまた起動して作業再開してアップロード…ということが出来なくなります（表情が消えるので）

Unityのバージョンは2019.4.31f1（VRChat推奨バージョン）
UniVRMは0.90.1、また使用している「VRMConveterForVRChat」はインストーラー版を用いております。

**Comment by Rikurus** [comment]
補足
この「編集の出来ないアニメーターコントローラー」は
右クリックで「ステートの作成」は行なえますが、そのステートの編集は行えないという状態です。

また、がとーしょこら氏作成の「[VRCAvatars3Tools](https://booth.pm/ja/items/2207020)」の「AnimatorControllerCombiner 」を用いて
「編集の出来ないアニメーターコントローラー」から「編集できるアニメーターコントローラー」へレイヤーをコピーさせた場合は編集可能になりました。

**Comment by esperecyan** [comment]
ご報告有り難うございます。検証してみます。

UnityのAnimatorControllerのGUID周りの不具合の可能性を考えていますが、回避できないか検討します。
