### ISSUE TITLE
blenderで編集したVRM→VRChatに変換したらエラーが来ました。

### ISSUE THREAD

**Issue by kaitakujp** [esperecyan/VRMConverterForVRChat#32]
いつもVRMConverterForVRChatを利用させてもらってるものです。

blenderで編集したVRMをVRChatに変換したらこのようなエラーが来ました。
「InvalidOperationException: Sequence contains no matching element」

新しくVRoidStudioがバージョンが上がっていたのでそれでモデルを作り、
blender28.3で編集していました。
いつものようにUnityでVRM→VRChatに変換したらなりました。

VRoidStudioの古いバージョンにしても
VRMConverterForVRChatのバージョンを下げてもダメでした。

ここでコメントをするのは初めてのわからないところもありますが、
このような対処法などがあれば教えてほしいです。

**Comment by kaitakujp** [comment]
そうですね、上記の方法でもやってみたのですが、それもうまくいかなかったです。

わたしが行ったことは
BlenderでVRMを読み込み編集し、VRMで出力して、VRMConverterForVRChatを入れた状態のUnityプロジェクトを
VRM0の項目からDuplicate and Convert for VRChatでVRChat用アバターに変換しようとしたらエラーが発生した感じです。

**Comment by esperecyan** [comment]
こちらのVRMファイルを、以下の手順で変換しましたが、問題なく変換できました。
https://github.com/esperecyan/VRMConverterForVRChat/files/8182816/Vita.zip

1. Blenderへインポート
2. Blenderでエクスポート
3. Unityへインポート
4. VRM Converter for VRChatで変換

環境は以下の通りです。
Blender 2.93.1
VRM Add-on for Blender 2.1.13
Unity 2019.4.31f1
VRChat SDK3-Avatars 2022.02.16.19.13
VRM Converter for VRChat 32.0.0

**Comment by esperecyan** [comment]
@kaitakujp こちらの問題は現在も発生しますか？　発生する場合はエラー全文の貼り付けをお願いします。

**Comment by esperecyan** [comment]
返信がないため閉じます。
