### ISSUE TITLE
standalone GUI for converting VRChat exports (.streammingasset) to VRM file

### ISSUE THREAD

**Issue by ghost** [esperecyan/VRMConverterForVRChat#36]
It would be nice to have a standalone GUI (without using Unity Editor) for converting VRChat exports (.streammingasset) to VRM file.

**Comment by esperecyan** [comment]
Does it mean ripping?

**Comment by Rikka93** [comment]
No.

**Comment by Rikka93** [comment]
Not necessarily. 

People sometimes share Unity exports for VRChat. Unity Editor is always required to open that export file. If a standalone GUI (Unity Player) could be used for the conversion, there is no need to install the Unity Editor (which is heavy).

**Comment by esperecyan** [comment]
I believe that sharing export data is a violation of the terms of the agreement.
https://hello.vrchat.com/legal/sdk
