### ISSUE TITLE
VRChat向けモデルをVRMコンバートする際、表情アニメーションに同名シェイプキーに対するパラメータ変更が複数あると、変換に失敗する

### ISSUE THREAD

**Issue by mew-ton** [esperecyan/VRMConverterForVRChat#39]
## エラーログ

画像でごめんなさい。手元の環境では問題を解消してしまったため、再現状態に戻すのが手間でやれてないです。

![image](https://user-images.githubusercontent.com/15868292/173224831-06f68399-cb79-4b65-a51d-f07ac2092af7.png)

## 発生時の状況

私の環境では以下のようなアニメーションを表情として使用していました。
後半部分のheadオブジェクトに対するアニメーションを削除したら再現しなくなりました。

![image](https://user-images.githubusercontent.com/15868292/173224724-edb0fd4a-41c4-4e14-be8a-1266910aea02.png)

C#については全く詳しくはないですが、

エラーログにある以下の文言と、
```
System.ArgumentException: An item with the same key has already been added. Key: f_point_R
```

発生元が
```
System.Collections.Generic.Dictionary.Add
```
であることから、表題の条件でエラーが発生すると推測されます。

**Comment by esperecyan** [comment]
ご報告有り難うございます。
https://github.com/esperecyan/VRMConverterForVRChat/issues/28#issuecomment-996770345 と同じエラーだと思うので再現できそうです。

**Comment by mew-ton** [comment]
はやい！確認ありがとうございます！！

**Comment by esperecyan** [comment]
「5000ポリNecoMaid」をVRM変換時に、表情へQuQu_RocknRollを指定すると再現。
https://sonovr.booth.pm/items/1843582
![](https://user-images.githubusercontent.com/3625160/179387768-97b97dbd-0595-46c1-b555-83fc533c1aa1.png)
