### ISSUE TITLE
VroidモバイルのVRMファイル対応

### ISSUE THREAD

**Issue by nuwaa** [esperecyan/VRMConverterForVRChat#4]
先日、Vroidモバイルで作ったアバターをVRMファイルとして出力できるようになりました。
[https://vroid.pixiv.help/hc/ja/articles/360000343262](url)

が、このVRMファイルをVRChatで使おうとVRMConverterForVRChatで変換にかけると、ここでハマってしまって、VRChatにアバターをアップロードすることができません。[Auto Fix]ボタンを押しても反応が無いのです。
![10CDD27D-F147-40B5-8F18-3255AC495B92](https://user-images.githubusercontent.com/3688822/99154375-b117cc00-26f2-11eb-9913-215549404d9a.jpeg)

ログを見てみるとこんなエラーが出ていました。
![63CAE126-0A08-47C8-91E2-B4D43BB44876](https://user-images.githubusercontent.com/3688822/99154423-0522b080-26f3-11eb-916f-4a53319120e3.png)
このフォルダには何のファイルも生成されていませんでした。

このあたりの解決に向けて、VRMConverterForVRChatの更新でご対応いただけませんでしょうか？

**Comment by esperecyan** [comment]
ご報告ありがとうございます。

VRoidモバイルのVRMファイルについて、UniVRMでのインポート時点で失敗しており、発生しているエラーはUniVRMのものです。

本件についてはUniVRMへissueを投稿済みです。
- https://github.com/vrm-c/UniVRM/issues/611 メッシュ名が「.」で始まるとインポートに失敗する

**Comment by nuwaa** [comment]
ご対応、ありがとうございます!

**Comment by esperecyan** [comment]
@nuwaa UniVRM-0.62.0で修正されたのでご報告します。
https://github.com/vrm-c/UniVRM/releases/tag/v0.62.0

**Comment by nuwaa** [comment]
@esperecyan ご連絡ありがとうございます!
私自身はこんな感じでメモっております。
https://note.com/nuwaa/n/n6f5959d02e18

**Comment by esperecyan** [comment]
コンバーターをご紹介いただきありがとうございます！

一応こちらのエラーですが、コンバーターがUniVRMを参照している部分でエラーが起きていたわけではなくて、VRMをUnityエディタへドロップした段階で、UniVRM単体で自動的に動作するインポート機能が失敗して、壊れたプレハブが生成されたという形になります。

**Comment by nuwaa** [comment]
@esperecyan 極力誤解を減らすよう、文面もちょっと変えました。
貴ツールでVRChatで利用できるよう変換はOKとなっていますが、まだエラー表示が出るので、気になってしまう人もいそうではあります。
が、Vroidモバイル→VRChatのルートでアバターを持ってくる人はまだまだ少ないので、ひとまずはここまででよろしいのではないかと思います。
