### ISSUE TITLE
シーン上のアバターを変換しようとすると例外「ArgumentNullException: Value cannot be null.」が発生する

### ISSUE THREAD

**Issue by Rikurus** [esperecyan/VRMConverterForVRChat#44]

**Comment by Rikurus** [comment]
誤って更新してしまいました。
お手数をお掛けいたします。

再現手順
1. VRoidStudioにてVRMファイルをエクスポートする
2. エクスポートしたVRMファイルを本ツール（VRMコンバーター）を用いて変換しようとする
3. 以下のようなエラーが発生する
![image](https://user-images.githubusercontent.com/51016253/177028924-fdd92bf1-20b7-4483-845c-8e5197ae22d8.png)

VRMファイルはVRoidStudioデフォルトの「白Tシャツ」でエクスポートしたものを使用しましたが、同じようにエラーになります。 
※VRoidStudioの設定によるものではないと思われます

**Comment by esperecyan** [comment]
こちらはシーンではなくアセット上のプレハブでもエラーが発生しますか？

【参照】
VRMからVRChatへアップロードする流れ - Qiita
https://qiita.com/100/items/7315fe3a7eb75732ae43

**Comment by Rikurus** [comment]
素早い回答ありがとうございます！

> こちらはシーンではなくアセット上のプレハブでもエラーが発生しますか？
試しに実行してみたところ、プロジェクトビュー内のアセットのプレハブを選択して実行したところ解決いたしました！
ありがとうございました！
※別のツールと使用方法を混同してしまったのかもしれません、ありがとうございます

**Comment by esperecyan** [comment]
確認ありがとうございます。
こちらの環境だと問題が再現しないので、引き続き調査します。

**Comment by esperecyan** [comment]
@expiation There seems to be an error when trying to convert an avatar on a scene. Please select the VRM prefab directly on Assets and convert it without instantiating the VRM prefab.

**Comment by esperecyan** [comment]
エラー全体を https://github.com/esperecyan/VRMConverterForVRChat/issues/45 から転載

> ArgumentNullException: Value cannot be null.
UniGLTF.UnityPath.FromAsset (UnityEngine.Object asset) (at Library/PackageCache/com.vrmc.gltf@0.99.2/Runtime/UniGLTF/IO/UnityPath.cs:350)
Esperecyan.Unity.VRMConverterForVRChat.UI.Wizard.GetAssetsPath (UnityEngine.GameObject vrm) (at Library/PackageCache/jp.pokemori.vrm-converter-for-vrchat@38.0.0/Editor/UI/Wizard.cs:698)
Esperecyan.Unity.VRMConverterForVRChat.UI.Wizard.OnWizardCreate () (at Library/PackageCache/jp.pokemori.vrm-converter-for-vrchat@38.0.0/Editor/UI/Wizard.cs:550)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at :0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at :0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at :0)
UnityEditor.ScriptableWizard.OnGUI () (at :0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at :0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at :0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at :0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at :0)
UnityEditor.HostView.Invoke (System.String methodName) (at :0)
UnityEditor.HostView.OldOnGUI () (at :0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at :0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at :0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at :0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at :0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at :0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at :0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at :0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at :0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at :0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at :0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at :0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at :0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at :0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at :0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at :0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at :0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at :0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at :0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <344226e341014466b33f0c0fa34fcef5>:0)

**Comment by yuusultu** [comment]
おかつゆうすです、同様の問題に引っかかりました。
samplescene上から複製して変換するを実行すると同様の不具合に遭遇。
![image](https://user-images.githubusercontent.com/16051050/178268232-6147910e-054b-4c54-9299-fc1e104dc683.png)
解決方法も上記に同じく、Projectファイル上から実施すれば問題ありませんでした。

Unity 2019.4.31.f1
Univrm 0.99.1(0.99.2でも同様の問題確認しました)
Vroidのバージョンは最新バージョンから落としてます。

**Comment by esperecyan** [comment]
VRoid Studio v1.10.0でVRMエクスポートした以下のモデルを変換しようとしたところ、確かに例外を再現できました

[VRoid Studio v1.10.0 test.zip](https://github.com/esperecyan/VRMConverterForVRChat/files/9127057/VRoid.Studio.v1.10.0.test.zip)

**Comment by esperecyan** [comment]
v38.0.1で修正しました。情報ありがとうございました。

再現できなかったのは、保存先パスがVRMの名前に対して保存・復元されていたからで、別名になったことで再現できるようになったようです。失礼いたしました。
