### ISSUE TITLE
メニューが出てこない不具合について

### ISSUE THREAD

**Issue by ciel4423** [esperecyan/VRMConverterForVRChat#5]
prefabをインポート後に「Duplicate and Convert for VRChat」を押すはずなのですが、メニューに該当の物が出てきません。SDK2（VRCSDK2-2020.12.09.04.45）やUniVRM（0.62.0）の最新バージョンでインポートしていて、インポートし直し等を試しても出てこないままです。
VRMConverterForVRChat自体も最新のv24.0.3で使用しています。
検索などで解決策を探してみましたが問題になりそうなインポート順も特に問題なさそうです。
ソースコードのフォルダ・ファイルを直接Assetsフォルダに入れてのインポートも試しましたがそれもダメでした。
何か解決策はないのでしょうか？

【エラーメッセージ】
Assets\VRMConverterForVRChat\Editor\Utilities\VRChatUtility.cs(207,20): error CS0120: An object reference is required for the non-static field, method, or property 'BaseConfig.HasKey(string)'
Assets\VRMConverterForVRChat\Editor\Utilities\VRChatUtility.cs(207,61): error CS0120: An object reference is required for the non-static field, method, or property 'BaseConfig.GetString(string)'

**Comment by ciel4423** [comment]
追記
BaseConfig.～のオブジェクトがないというエラーだったので、オブジェクトを作る方法でエラーが消え解決しました。
お手数おかけしました。

**Comment by esperecyan** [comment]
ご報告ありがとうございます。v24.1.0で対応いたしました。
