### ISSUE TITLE
Allow exporting meshes without combining

### ISSUE THREAD

**Issue by fire** [esperecyan/VRMConverterForVRChat#50]
Hi, can you export meshes without combining and splitting blend shapes into 2 meshes?

I need to do this because I want to edit the mesh in blender in https://github.com/saturday06/VRM_Addon_for_Blender

For example a boolean to disable or enable mesh merging.

**Comment by esperecyan** [comment]
The conversion to VRM is only intended to provide a simple conversion for beginner beginners.

The VRM format is intended to be the final output format for avatars, not for additional editing.
If you want to use it in Blender, why not import it without going through VRM?

**Comment by fire** [comment]
Because the original format is unity package.

**Comment by esperecyan** [comment]
Does that mean that the extension of the mesh is `.asset`, as it is when imported with UniVRM, for example?
If so, you could use the FBX Exporter, or if you prefer, UniVRM.
https://docs.unity3d.com/Packages/com.unity.formats.fbx@4.2

**Comment by fire** [comment]
Those routes do not access the code translating VRCDescriptor into VRM meta.

**Comment by esperecyan** [comment]
As mentioned above, exporting for Blender is not the purpose of this script and I do not intend to implement it.

**Comment by fire** [comment]
I disagree. However, I respect your wishes.
