### ISSUE TITLE
Bodysuit clothing doesn't transfer properly onto vrchat

### ISSUE THREAD

**Issue by HugoPere** [esperecyan/VRMConverterForVRChat#53]
Well, I updated the converter (from unity, so v 38.2.1)
And decided to make an avatar with Vroid's bodysuit, but once uploaded the model showed like this.
I tried re-importing the model, take out all custom animations, make a new project, but this still fails.

Are bodysuits not supported?

![image](https://user-images.githubusercontent.com/50475071/213730784-dac7bfd8-0a29-4083-a2d9-02d0095a40fd.png)
![image](https://user-images.githubusercontent.com/50475071/213731271-a3d6cc5b-427a-40ed-a047-0ae87bdc66b7.png)
![image](https://user-images.githubusercontent.com/50475071/213731345-a6b19c0b-1d45-4f51-902b-63e5ab78149a.png)

**Comment by esperecyan** [comment]
Does the model work properly with other applications supporting VRM?
Are you importing VRM file into Unity and converting the generated VRM prefabs as is?

Also, is there any way to reproduce the issue on my end?

**Comment by HugoPere** [comment]
Well, tried Vseeface now (used a exported vrm (not from the hub)) and it works.
A way to reproduce it would be to upload an avatar that has bodysuit/jumpsuit as clothing, the model I uploaded also has a material change function (but also tried without that function)

And the way I do it is: 
> open project
> make a folder for the avi
> drag vrm,  then duplicate and convert for vrchat
> use the vrchat prefab (created with the conversion)

**Comment by esperecyan** [comment]
In VRoid Studio 1.19.0, which means bodysuit/jumpsuit?

Can you attach a ZIP file of the VRM file that reproduces the issue to your comment?

![](https://user-images.githubusercontent.com/3625160/213951167-e67098f2-17c4-49a7-bbee-dde566a97457.png)

**Comment by HugoPere** [comment]
I mean leathersuit/jumpsuit
It's in dresses.
And here's a zip with the vrm, straight from the unity project, it has 2 materials 
![image](https://user-images.githubusercontent.co
[scourge.zip](https://github.com/esperecyan/VRMConverterForVRChat/files/10476299/scourge.zip)
m/50475071/213956624-9ee06d26-ee4b-4f1d-99de-058f78a39c70.png)

**Comment by HugoPere** [comment]
![image](https://user-images.githubusercontent.com/50475071/213957300-878ccf38-b053-439c-9c83-71de43977076.png)
Well, the image didn't upload correctly

**Comment by esperecyan** [comment]
Thank you for providing the VRM file.
I have converted and uploaded the file and have not identified any problems. The location is the default home world.

The following is the prefab I converted.
https://github.com/esperecyan/VRMConverterForVRChat/files/10485836/scourge.unitypackage.zip

My environment is as follows.
- VRM Converter for VRChat 38.2.1
- UniVRMExtensions 7.3.0
- UniVRM-0.99.4
- VRChat: Build 1275
- VRChat SDK - Base 3.1.10
- VRChat SDK -Avatars 3.1.10
- VRChat Package Resolver Tool 0.1.17
- VRChat Creator Companion 1.0.6
- Unity 2019.4.31f1
- Windows 10 22H2
- NVIDIA GeForce GTX 3080
- GeForce Game Ready Driver 528.02

![](https://user-images.githubusercontent.com/3625160/214200137-d41e4d16-3f43-4dc6-aff0-e29d4e01cb6d.png)

**Comment by HugoPere** [comment]
Huh, that's wierd, then it was something on my configuration?
Gonna try it again then.
Thanks for your time and answers!!
