### ISSUE TITLE
"IsUnderAssetsFolder" property is not available since com.vrmc.gltf v0.107.0.

### ISSUE THREAD

**Issue by Sonic853** [esperecyan/VRMConverterForVRChat#55]
Yes, com.vrmc.gltf package uses the "IsUnderWritableFolder" property instead of "IsUnderAssetsFolder" from v0.107.0:

https://github.com/vrm-c/UniVRM/blob/1a192d2f93b5a8a07f9906e0552527d06838ada0/Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs#L42-L72

Code still using the "IsUnderAssetsFolder" property:

https://github.com/esperecyan/VRMConverterForVRChat/blob/af3c8d35fbb6ce3c06cbb1f47c434ef7110376a5/Editor/Duplicator.cs#L121

https://github.com/esperecyan/VRMConverterForVRChat/blob/af3c8d35fbb6ce3c06cbb1f47c434ef7110376a5/Editor/Duplicator.cs#L279-L307

**Comment by esperecyan** [comment]
This is due to the fact that the latest VRChat SDK depends on a very old Unity version that no longer has security updates.

Please vote for the post on Canny below.
https://feedback.vrchat.com/feature-requests/p/update-to-unity-20213-lts
