### ISSUE TITLE
Pelvis and Thigh Bone Angle 0 Degrees / 骨盤と大腿骨の角度0度

### ISSUE THREAD

**Issue by alu-potato** [esperecyan/VRMConverterForVRChat#6]
Many VRMs imported with this tell me that the angle is not correct. Is this a problem with the VRM model itself or the software?

![image](https://user-images.githubusercontent.com/54824150/104658297-1a32a600-5688-11eb-91d8-7d13583f3424.png)

これでインポートされた多くのVRMは、角度が正しくないことを教えてくれます。これはVRMモデル自体またはソフトウェアの問題ですか？

(私はGoogle翻訳を使用しました)

**Comment by esperecyan** [comment]
これはおそらく、角度の計算を誤っている (local rotationに依存している) ことに起因するVRChat SDK側のバグです。VRMではモデルが正規化されているため、local rotationに基づいて角度を算出すれば必ず0.0になります。
