### ISSUE TITLE
依存関係にあるUniVRM0.119.0にも正規化不具合があるらしい

### ISSUE THREAD

**Issue by FujiSunflower** [esperecyan/VRMConverterForVRChat#65]
依存関係にあるUniVRM0.119.0にも正規化不具合があるらしいです。
緊急度は高くないと思うので話題共有としてのissue立てです。

**Comment by esperecyan** [comment]
v41.2.0でシェイプキーの正規化周りの不具合が解消されたと思われるUniVRM-0.125.0へ依存するようにしました。
