### ISSUE TITLE
NotImplementedException: The method or operation is not implemented. UniGLTF.UnityPath.GetAssetFolder (System.String suffix) (at Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs:181) VRM.VRMEditorImporterContext.ConvertAndExtractImages (UniGLTF.UnityPath assetPath, System.Action`1[T] onTextureReloaded) (at Assets/VRM/Editor/Format/VRMEditorImporterContext.cs:154) VRM.VRMImporterMenu.ImportMenu () (at Assets/VRM/Editor/Format/VRMImporterMenu.cs:77)

### ISSUE THREAD

**Issue by Hardcase0701** [esperecyan/VRMConverterForVRChat#7]
Hello, i try to import my vrm file with your vrm converter, but i cant do that because of the message, that is in the title. Could you maybe help me? Thanks in advance.

**Comment by esperecyan** [comment]
UniVRM, which imports VRMs, is just included in the unitypackage of BOOTH/VketStore and is not developed in this repository. Report any UniVRM issues to https://github.com/vrm-c/UniVRM .
