### ISSUE TITLE
Assetsへのvrmファイルの読み込み時のエラー

### ISSUE THREAD

**Issue by Mappy00** [esperecyan/VRMConverterForVRChat#8]
![image](https://user-images.githubusercontent.com/80631535/111071018-970ebe80-8517-11eb-891e-a45b7b45dc2b.png)
記載の手順「VRMからVRChatへアップロードする流れ」
https://qiita.com/100/items/7315fe3a7eb75732ae43
に沿って操作をしましたが、Assetsにvrmファイルをドラックドロップ時に画像のようなエラーが出てしまいました。何度かやり直してみましたが、自分自身がUnityに慣れていないということもあり原因がわからない状態です。

**Comment by Mappy00** [comment]
追記 2021/3/15

詳しい手順を記述していなかったので追記いたします。

【使用したもの】
• Unity 2018.4.20f1
• VRChat SDK2 VRCSDK2-2021.03.09.13.58_Public.unitypackage
• VRM Converter for VRChat-25.3.0 + UniVRMExtensions-1.6.2 + UniVRM-0.68.0.unitypackage
• VRoidStudio 0.13.1
• VRoidStudioでエクスポートしたサンプルモデル Vivi.vrm

【実行手順】
1.Unity 2018.4.20f1をインストール。
2.Vrchat公式サイトから最新のSDK2をダウンロード。
3.VRM Converter for VRChatをダウンロード。
4.新規作成 2018.4.20f1を選択。
5.AssetsにSDK2をドラックドロップ＆インポート。
6.AssetsにVRM Converter for VRChat + UniVRMExtensions + UniVRMをドラックドロップ＆インポート。
7.Assetsにvrmファイルをドラックドロップ。
↑vrmファイルが正しく読み込まれない。

【補足】
Unity 2018.4.20f1で別プロジェクトを作成して UniVRM-0.66.0_39d5.unitypackage（作成していただいたConverterに付属しているUniVRMとは別のバージョン）だけを読み込ませて、同じvrmファイルをドラックドロップしたところ正しく読み込まれることを確認いたしました。

**Comment by esperecyan** [comment]
ご報告ありがとうございます。
BOOTH/VketStoreにおいて、UniVRM-0.68.2を同梱するようにしました。

**Comment by Mappy00** [comment]
ご対応ありがとうございました！🙏
