### ISSUE TITLE
Version dont seem to work?

### ISSUE THREAD

**Issue by Peptic52** [esperecyan/VRMConverterForVRChat#9]
I tried downloading the latest version of the converts and Unity wont take it so I went into previous version and downloaded  the 24.0.2 Version which is what in tutorials seem to work. But its a File now not like the other ones. So far I cant get any to work. Just bad luck or is there a fix i dont know about?

**Comment by esperecyan** [comment]
I have confirmed that VRM Converter for VRChat 25.3.0 works properly with the following environment.
- Unity 2018.4.20f1
- VRChat SDK3-Avatars 2021.03.22.18.27
- UniVRM 0.69.1
- Windows 10 2004 64bit

Please provide the following information.
- Unity, VRChat SDK, UniVRM, VRM Converter for VRChat, and OS versions
- What operation you performed
- What happened as a result of the operation
- What kind of result you are expecting
